ALTER TABLE users
ADD COLUMN IF NOT EXISTS github_id VARCHAR(100) UNIQUE,
ADD COLUMN IF NOT EXISTS github_username VARCHAR(100),
ADD COLUMN IF NOT EXISTS github_avatar_url TEXT,
ADD COLUMN IF NOT EXISTS github_access_token TEXT,
ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE,
ADD COLUMN IF NOT EXISTS google_avatar_url TEXT;
